group 'me.yohom.amap_search_fluttify'
version '1.0-SNAPSHOT'

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'me.yohom.amap_search_fluttify'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.jniLibs.srcDir 'libs'
    }
    defaultConfig {
        minSdk 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lint {
        disable 'InvalidPackage'
    }
    packaging {
        resources {
            merges += ['res/values/values.xml', 'AndroidManifest.xml', 'R.txt', 'classes.jar', 'proguard.txt']
        }
    }
    buildTypes {
        release {
            consumerProguardFiles "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation 'androidx.annotation:annotation:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.20"
    compileOnly rootProject.findProject(":foundation_fluttify")
    api 'com.amap.api:search:9.2.0'
}
