// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapDrivingRouteShowFieldType {
  AMapDrivingRouteShowFieldTypeNone /* 1<<0 */,
  AMapDrivingRouteShowFieldTypeCost /* 1<<1 */,
  AMapDrivingRouteShowFieldTypeTmcs /* 1<<2 */,
  AMapDrivingRouteShowFieldTypeNavi /* 1<<3 */,
  AMapDrivingRouteShowFieldTypeCities /* 1<<4 */,
  AMapDrivingRouteShowFieldTypePolyline /* 1<<5 */,
  AMapDrivingRouteShowFieldTypeNewEnergy /* 1<<6 */,
  AMapDrivingRouteShowFieldTypeAll /* ~0 */
}

extension AMapDrivingRouteShowFieldTypeToX on AMapDrivingRouteShowFieldType {
  int toValue() {
    switch (this) {
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeNone:
        return 1;
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeCost:
        return 2;
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeTmcs:
        return 4;
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeNavi:
        return 8;
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeCities:
        return 16;
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypePolyline:
        return 32;
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeNewEnergy:
        return 64;
      case AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeAll:
        return -1;
      default:
        return 0;
    }
  }
}

extension AMapDrivingRouteShowFieldTypeFromX on int {
  AMapDrivingRouteShowFieldType toAMapDrivingRouteShowFieldType() {
    switch (this) {
      case 1:
        return AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeNone;
      case 2:
        return AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeCost;
      case 4:
        return AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeTmcs;
      case 8:
        return AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeNavi;
      case 16:
        return AMapDrivingRouteShowFieldType
            .AMapDrivingRouteShowFieldTypeCities;
      case 32:
        return AMapDrivingRouteShowFieldType
            .AMapDrivingRouteShowFieldTypePolyline;
      case 64:
        return AMapDrivingRouteShowFieldType
            .AMapDrivingRouteShowFieldTypeNewEnergy;
      case -1:
        return AMapDrivingRouteShowFieldType.AMapDrivingRouteShowFieldTypeAll;
      default:
        return AMapDrivingRouteShowFieldType.values[this + 1];
    }
  }
}
